### ISSUE TITLE
Do you have GPT model for mlmodel or tflite to run in the mobile device?

### ISSUE THREAD

**Issue by tucan9389** [aespinilla/GPT3-Tokenizer#7]
Thanks for sharing your fantastic effort.

I’m looking for how to run the GPT3 model on iOS devices.

Do you have a pre-trained GPT mlmodel or tflite model?
Or could you share the original model repository you referred to when you implemented this?

Thank you again.

**Comment by aespinilla** [comment]
Hi! Thanks for visit my repo!

Sorry i haven't got any gpt ml model but there is a repository which could be useful: [https://github.com/latitudegames/GPT-3-Encoder](https://github.com/huggingface/swift-coreml-transformers)

This project is based on this project written in javascript [https://github.com/latitudegames/GPT-3-Encoder](https://github.com/latitudegames/GPT-3-Encoder)

**Comment by tucan9389** [comment]
Oh, I see. Thank you for letting me know :)
